### ISSUE TITLE
Download link isn't working.

### ISSUE THREAD

**Issue by mtaha3249** [syedshoaibmansoor/Helper-Utility#2]
Hi developer, Download package link isn't working.

While I was working on making module I make release. You can do that. too. Follow [this](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository), it might help.

Let me know, when fixed, I wanna try it.

**Comment by syedshoaibmansoor** [comment]
Hello @mtaha3249 ,

I have added the Unity Package along with the source code in a the release section. Kindly download it from there.

Thank you
